server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name 157.10.161.95 _;

    root /var/www/html/hodjapa-food;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}