server {
    server_name hodjapafood.shop www.hodjapafood.shop;

    root /var/www/html/hodjapa-food;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/hodjapafood.shop/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/hodjapafood.shop/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    listen 80;
    listen [::]:80;
    server_name hodjapafood.shop www.hodjapafood.shop;
    return 301 https://$host$request_uri;
}